name: Linter

on:
    push:
        tags:
            - v*
        branches:
            - master
    pull_request:

permissions:
    contents: read

jobs:
    golangci:
        strategy:
            matrix:
                go: [1.17]
                os: [ubuntu-latest, windows-latest]

        name: lint
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go }}
            - uses: actions/checkout@v3
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.29
                  args: --verbose
